# Generated by Django 4.0.6 on 2022-08-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroup',
            name='name',
            field=models.CharField(default='Saturday, 06. August 2022. 04:27PM 54', max_length=100),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='slug',
            field=models.SlugField(default='Saturday-06-August-2022-04-27PM-54', max_length=200),
        ),
    ]
