# Generated by Django 4.0.6 on 2022-08-06 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_taskgroup_name_alter_taskgroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroup',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 8, 6, 16, 39, 15, 886661), max_length=100),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='slug',
            field=models.SlugField(default='Saturday-06-August-2022-04-39PM-15', max_length=200),
        ),
    ]
