# Generated by Django 4.0.6 on 2022-08-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_taskgroup_name_alter_taskgroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroup',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
